### ISSUE TITLE
Update unsafe lifecycles

### ISSUE THREAD

**Issue by diegohaz** [scniro/react-codemirror2#134]
When using `react-codemirror2` within `<StrictMode />` or with React `v16.9.0`, it shows a few warnings on the console:

```
Warning: componentWillMount is deprecated and will be removed in the next major version. Use componentDidMount instead. As a temporary workaround, you can rename to UNSAFE_componentWillMount.

Please update the following components: Controlled

Learn more about this warning here:
https://fb.me/react-async-component-lifecycle-hooks
```

```
Warning: componentWillReceiveProps is deprecated and will be removed in the next major version. Use static getDerivedStateFromProps instead.

Please update the following components: Controlled

Learn more about this warning here:
https://fb.me/react-async-component-lifecycle-hooks
```

**Comment by scniro** [comment]
@diegohaz thanks for bringing this to my attention. Should be fixed in the [6.0.0](https://github.com/scniro/react-codemirror2/releases/tag/6.0.0) release 👍

**Comment by diegohaz** [comment]
Awesome. Thank you for maintaining this lib. 🙌

**Comment by diegohaz** [comment]
Hmm. I'm still get the warning, but there's an additional component now (`SideEffect(NullComponent)`):
```
Warning: componentWillMount is deprecated and will be removed in the next major version. Use componentDidMount instead. As a temporary workaround, you can rename to UNSAFE_componentWillMount.

Please update the following components: SideEffect(NullComponent)

Learn more about this warning here:
https://fb.me/react-async-component-lifecycle-hooks
```
```
Warning: componentWillReceiveProps is deprecated and will be removed in the next major version. Use static getDerivedStateFromProps instead.

Please update the following components: Controlled

Learn more about this warning here:
https://fb.me/react-async-component-lifecycle-hooks
```

**Comment by scniro** [comment]
Interesting, surprised they are doing away with those ones too. Okay, will reopen and fix this up soon thanks for the detail.

**Comment by nickbeaulieu** [comment]
Is it possible to revisit this issue soon? I would like to use this package but I am not sure it is being actively maintained. Thanks!

**Comment by jestapinski** [comment]
Agreed, I see #151 for `componentWillReceiveProps` and am curious if we could get this released.

**Comment by ldeveber** [comment]
We are seeing this a lot and are wondering when a fix will be available?

**Comment by kaniseo** [comment]
Is it possible to merge #151? Or get a fix for this? Would really like to use this library but reluctant since componentWillReceiveProps will not work at all after React 17 release

**Comment by Janpot** [comment]
fyi https://github.com/scniro/react-codemirror2/pull/151 will not work in react 17 either.

**Comment by kaniseo** [comment]
I don't know if they said something else somewhere but their blog says

> The new names like UNSAFE_componentWillMount will keep working in both React 16.9 and in React 17.x

from https://reactjs.org/blog/2019/08/08/react-v16.9.0.html

**Comment by scniro** [comment]
@diegohaz @nickbeaulieu @ldeveber @kaniseo @Janpot I am a lot shorter on time these days as when I started this project. Codemirror & React APIs are moving to quickly for me to keep atop of for the day-to-day. I am looking for a co-maintainer of this project. Please contact me directly if you are interested. Thank you for understanding.

**Comment by fongandrew** [comment]
This should be resolved with #176 and v6.0.1 / v7.
